# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=19)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('mark_favorite', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(choices=[('BR', 'Breakfast'), ('LA', 'Launch'), ('DI', 'Dinner'), ('DE', 'Delivery'), ('CA', 'Cafe'), ('LU', 'Luxury Dining'), ('NI', 'Night Life')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('vote', models.SmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=5)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('slug', models.SlugField(max_length=120)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OperatingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('lag', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('phone_number', models.PositiveIntegerField()),
                ('owner_email', models.EmailField(max_length=254)),
                ('opening_status', models.IntegerField(choices=[(1, 'open'), (2, 'closed')], default=1)),
                ('website', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload/products/%Y/%m/%d')),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=15, null=True)),
                ('other_details', models.TextField()),
                ('is_parking', models.BooleanField(default=False)),
                ('is_wifi', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(related_name='restaurants_features', to='restaurants.FeatureChoice')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TimingChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timings', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timings',
            field=models.ManyToManyField(related_name='restaurants_timings', to='restaurants.TimingChoice'),
        ),
        migrations.AddField(
            model_name='operatingtime',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_time', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurants.MenuCategory'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('id', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='restaurant',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterIndexTogether(
            name='menu',
            index_together=set([('id', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set([('restaurant', 'ip')]),
        ),
    ]
