# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
