# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(max_length=300),
        ),
    ]
