# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20160816_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
