# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='rate',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='rate',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
